#! /bin/bash
compton &
nitrogen --restore &

dwmblocks &

#OTBdwmbar &

#dwmblocks
#/home/vijay/dwm-bar/dwm_bar.sh &
#dwmstatus 2>&1 >/dev/null &


while true; do
	dwm >/dev/null 2>&1

done

exec dwm
