#!/bin/bash

while true; do
	dwmweather > /home/vijay/dotfiles/dwmscripts/dwmweather.txt
	dwmupdates > /home/vijay/dotfiles/dwmscripts/dwmupdates.txt

	sleep 3600s

done &

while true; do
	WEATHER=$(< /home/vijay/dotfiles/dwmscripts/dwmweather.txt)
	VOL=$(dwmvol)
	CPU=$(dwmcpu)
	MEM=$(dwmmemory)
#	NET=$(dwmnet)
#	TEMP=$(dwmtemp)
	HDD=$(dwmdisk)
	UPDATES=$(< /home/vijay/dotfiles/dwmscripts/dwmupdates.txt)
	TIME=$(dwmclock)
	BATTERY=$(dwmbattery)
	xsetroot -name "|$BATTERY|$WEATHER|$CPU|$MEM|$HDD|$UPDATES|$VOL|$TIME"

	sleep 5s
	
done &
